GET http://localhost:8080/smallDogs
###

GET http://localhost:8080/smallDogs/652af7c96a79f865056c12f4
###

POST http://localhost:8080/smallDogs HTTP/1.1
content-type: application/json

{
    "name": "Daisy",
    "breed": "Chihuahua",
    "classification": "small",
    "gender": "Female",
    "age": "Adult",
    "furColor": "Tan",
    "weight": 12
}

###

PUT http://localhost:8080/smallDogs/652af7c96a79f865056c12f4 HTTP/1.1
content-type: application/json

{
    
    "name": "Taquito",
    "breed": "Chihuahua",
    "classification": "small",
    "gender": "Male",
    "age": "Adult",
    "furColor": "Brown",
    "weight": "12 lbs."
    
}

###
DELETE http://localhost:8080/smallDogs/652b77416708b85380c16e5c 

###

GET https://dog-adoption.onrender.com/smallDogs HTTP/1.1
content-type: application/json
###

GET https://dog-adoption.onrender.com/smallDogs/652af7c96a79f865056c12f4 HTTP/1.1
content-type: application/json
###

POST https://dog-adoption.onrender.com/smallDogs HTTP/1.1
content-type: application/json

{
    "name": "Daisy",
    "breed": "Chihuahua",
    "classification": "small",
    "gender": "Female",
    "age": "Adult",
    "furColor": "Brown",
    "weight": "10 lbs."
}
###

PUT https://dog-adoption.onrender.com/smallDogs/652b78d7b4da141f0db831f7 HTTP/1.1
content-type: application/json

{
    
    "name": "Daisy",
    "breed": "Chihuahua",
    "classification": "small",
    "gender": "Male",
    "age": "Adult",
    "furColor": "Brown",
    "weight": "10 lbs."
    
}

###

DELETE https://dog-adoption.onrender.com/smallDogs/652b78d7b4da141f0db831f7

###